import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Header from './components/Layout/Header'
import Footer from './components/Layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gabriel Mazieri',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-sky-200 flex flex-col justify-center items-center content-center">
        <div className="flex flex-col justify-center border-solid items-center content-center">
          <Header></Header>

          {children}

          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
