import type { Metadata } from 'next'
import './globals.css'

import { Open_Sans } from "next/font/google"
import Header from './components/Layout/Header'
import Footer from './components/Layout/Footer'

const font = Open_Sans({ fallback: ["system-ui", "sans-serif"], subsets: ['latin'], variable:"--font-open-sans" })

export const metadata: Metadata = {
  // title: 'Gabriel Mazieri',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${font.variable} font-sans`}>
        <div>
          <Header></Header>

          {children}

          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
